# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsn <- function(r, xi, omega, alpha) {
    .Call('_ComputingClubRcpp_dsn', PACKAGE = 'ComputingClubRcpp', r, xi, omega, alpha)
}

rcpp_hello_world <- function() {
    .Call('_ComputingClubRcpp_rcpp_hello_world', PACKAGE = 'ComputingClubRcpp')
}

